version: 0.0
os: windows
files:
  - source: \publish_output
    destination: c:\inetpub\wwwroot\8392DSCC\DSCC.8392.FrontEnd
  - source: \scripts\deletewebsite.ps1
    destination: c:\temp
  - source: \scripts\installwebsite.ps1
    destination: c:\temp
  - source: \scripts\deletewebsite.bat
    destination: c:\temp
  - source: \scripts\installwebsite.bat
    destination: c:\temp
  - source: \appspec.yml
    destination: c:\inetpub\wwwroot\8392DSCC
hooks:
  BeforeInstall:
    - location: \scripts\deletewebsite.bat
      timeout: 180
  AfterInstall:
    - location: \scripts\installwebsite.bat
      timeout: 180